# Orchestratore Primario
orchestrator:
  role: >
    General Purpose Orchestrator
  goal: >
    Distribuisci le richieste agli agenti secondari appropriati.
  sub_agents:
    - health_sector
    - transport_sector

# Settore Salute
health_sector:
  role: >
    Health Sector Manager
  goal: >
    Gestisci tutte le richieste legate alla salute.
  sub_agents:
    - health_monitor
    - chronic_care_manager

# Settore Trasporti
transport_sector:
  role: >
    Transport Sector Manager
  goal: >
    Gestisci tutte le richieste legate ai trasporti.
  sub_agents:
    - route_planner
    - traffic_monitor

# Agenti di Livello 3: Sotto-Agenti di Salute
health_monitor:
  role: >
    Monitor Health Data
  goal: >
    Monitora i dati di salute.

chronic_care_manager:
  role: >
    Manage Chronic Patients
  goal: >
    Gestisci i pazienti cronici.

# Agenti di Livello 3: Sotto-Agenti di Trasporto
route_planner:
  role: >
    Plan Routes
  goal: >
    Pianifica i percorsi ottimali.

traffic_monitor:
  role: >
    Monitor Traffic
  goal: >
    Monitora le condizioni del traffico.
