tools:
  openrouter_tool:
    name: "OpenRouter API Tool"
    description: >
      Questo tool utilizza l'API di OpenRouter per generare completamenti di testo o rispondere a domande.
    module: "tools.openrouter_tool"
    function: "call_openrouter"

  data_tool:
    name: "Health Data Fetcher"
    description: >
      Raccoglie dati sanitari dai dispositivi wearable o database medici.
    module: "tools.data_tool"
    function: "fetch_health_data"

  routing_tool:
    name: "Request Router Tool"
    description: >
      Determina quale agente deve essere chiamato in base alla categoria della richiesta.
    module: "tools.routing_tool"
    function: "route_request"
